[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100

[tool.coverage.run]
parallel = true
branch = true
source = ["dictpymap"]

[tool.coverage.paths]
source = ["src", ".tox/*/site-packages"]
